import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "sonner";
import LayoutProvider from "./components/LayoutProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <LayoutProvider>
            <html lang="en">
                <body className={`antialiased`}>
                    <Toaster />
                    <Navbar />
                    {children}
                </body>
            </html>
        </LayoutProvider>
    )
}
