import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { SanityLive } from "@/sanity/lib/live";
import LayoutProvider from "@/components/LayoutProvider";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <LayoutProvider>
            <html lang="en">
                <body>
                    <Header />
                    {children}
                    <SanityLive />
                    <Toaster />
                </body>
            </html>
        </LayoutProvider>
    )
}
