name: Node.js CI Full

on:
  push:
    branches: ["main"]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [23.x]
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{secrets.NEXT_PUBLIC_SANITY_PROJECT_ID}}
      NEXT_PUBLIC_SANITY_DATASET: ${{secrets.NEXT_PUBLIC_SANITY_DATASET}}
      NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
      SANITY_STUDIO_PROJECT_ID: ${{secrets.SANITY_STUDIO_PROJECT_ID}}
      SANITY_STUDIO_DATASET: ${{secrets.SANITY_STUDIO_DATASET}}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
      CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
      SANITY_API_TOKEN: ${{secrets.SANITY_API_TOKEN}}
      SANITY_API_READ_TOKEN: ${{secrets.SANITY_API_READ_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: cd /var/www/html/stamco
      - run: pm2 restart 0
